nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
        origin_regex: true
    paths:
        '^/api/':
            allow_origin: ['^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$']
            allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            expose_headers: ['Link']
            max_age: 3600
            origin_regex: true
